repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/mondeja/hledger-fmt
    rev: v0.3.9
    hooks:
      - id: hledger-fmt       # Use this id to format files in place
